### ISSUE TITLE
Operator error when trying to create registry

### ISSUE THREAD

**Issue by wackazong** [lsst-sqre/strimzi-registry-operator#100]
I installed a Kafka cluster successfully.

I deployed the strimzi-registry-operator using https://github.com/lsst-sqre/strimzi-registry-operator/issues/79#issuecomment-1365260271

I create a topic and a KafkaUser in the namespace of the kafka cluster. I then define a StrimziSchemaRegistry resource in the same namespace. 

I get the following error in the oprator log:

```
[2023-05-09 22:04:34,392] kopf.objects         [DEBUG   ] [kafka/confluent-schema-registry] Patching with: {'metadata': {'annotations': {'kopf.zalando.org/touch-dummy': '2023-05-09T22:04:34.391801'}}, 'status': {'kopf': {'dummy': '2023-05-09T22:04:34.391801'}}}
[2023-05-09 22:04:34,419] kopf.objects         [WARNING ] [kafka/confluent-schema-registry] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-05-09T22:04:34.391801'}}, None),)
[2023-05-09 22:04:34,524] kopf.objects         [DEBUG   ] [kafka/confluent-schema-registry] Creation is in progress: {'apiVersion': 'roundtable.lsst.codes/v1beta1', 'kind': 'StrimziSchemaRegistry', 'metadata': {'annotations': {'kopf.zalando.org/create_registry': '{"started":"2023-05-09T21:05:22.061647","delayed":"2023-05-09T22:04:34.354321","purpose":"create","retries":73,"success":false,"failure":false,"message":"(404)\\nReason: Not Found\\nHTTP response headers: HTTPHeaderDict({\'Audit-Id\': \'ea2cad20-6bd0-4489-b9e8-52ece4ae6efe\', \'Cache-Control\': \'no-cache, private\', \'Content-Type\': \'application/json\', \'X-Kubernetes-Pf-Flowschema-Uid\': \'dc0327c8-640d-4099-9826-fd4709b6d952\', \'X-Kubernetes-Pf-Prioritylevel-Uid\': \'52a754a4-bd10-4e90-ba33-04ea09f638b7\', \'Date\': \'Tue, 09 May 2023 22:03:34 GMT\', \'Content-Length\': \'224\'})\\nHTTP response body: b\'{\\"kind\\":\\"Status\\",\\"apiVersion\\":\\"v1\\",\\"metadata\\":{},\\"status\\":\\"Failure\\",\\"message\\":\\"secrets \\\\\\\\\\"confluent-schema-registry\\\\\\\\\\" not found\\",\\"reason\\":\\"NotFound\\",\\"details\\":{\\"name\\":\\"confluent-schema-registry\\",\\"kind\\":\\"secrets\\"},\\"code\\":404}\\\\n\'\\n"}', 'kopf.zalando.org/touch-dummy': '2023-05-09T22:04:34.391801', 'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"roundtable.lsst.codes/v1beta1","kind":"StrimziSchemaRegistry","metadata":{"annotations":{},"name":"confluent-schema-registry","namespace":"kafka"},"spec":{"compatibilityLevel":"forward","listener":"tls","securityProtocol":"PLAINTEXT","strimziVersion":"v1beta2"}}\n'}, 'creationTimestamp': '2023-05-09T21:05:21Z', 'generation': 5, 'managedFields': [{'apiVersion': 'roundtable.lsst.codes/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:compatibilityLevel': {}, 'f:cpuLimit': {}, 'f:cpuRequest': {}, 'f:listener': {}, 'f:memoryLimit': {}, 'f:memoryRequest': 
{}, 'f:registryImage': {}, 'f:registryImageTag': {}, 'f:securityProtocol': {}, 'f:serviceType': {}, 'f:strimzi-version': {}, 'f:strimziVersion': {}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2023-05-09T22:03:58Z'}, {'apiVersion': 'roundtable.lsst.codes/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'f:kopf.zalando.org/create_registry': {}, 'f:kopf.zalando.org/touch-dummy': {}}}}, 'manager': 'kopf', 'operation': 'Update', 'time': '2023-05-09T22:04:34Z'}], 'name': 'confluent-schema-registry', 'namespace': 'kafka', 'resourceVersion': '50816', 'uid': 'fd9c7949-1c48-44a7-9b69-2facc4d8df69'}, 'spec': {'compatibilityLevel': 'forward', 'cpuLimit': '', 'cpuRequest': '', 'listener': 'tls', 'memoryLimit': '', 'memoryRequest': '', 'registryImage': 'confluentinc/cp-schema-registry', 'registryImageTag': '7.2.1', 'securityProtocol': 'PLAINTEXT', 'serviceType': 'ClusterIP', 'strimzi-version': 'v1beta2', 'strimziVersion': 'v1beta2'}}
2023-05-09T22:04:34.525770275Z [2023-05-09 22:04:34,524] kopf.objects         [DEBUG   ] [kafka/confluent-schema-registry] Handler 'create_registry' is invoked.
[2023-05-09 22:04:34,526] kopf.objects         [INFO    ] [kafka/confluent-schema-registry] Creating a new Schema Registry deployment: confluent-schema-registry with listener=tls (security protocol=PLAINTEXT) and strimzi-version=v1beta2 serviceType=ClusterIP image=confluentinc/cp-schema-registry:7.2.1
[2023-05-09 22:04:34,554] kubernetes.client.re [DEBUG   ] response body: {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"KafkaUser","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"kafka.strimzi.io/v1beta2\",\"kind\":\"KafkaUser\",\"metadata\":{\"annotations\":{},\"labels\":{\"strimzi.io/cluster\":\"my-cluster\"},\"name\":\"confluent-schema-registry\",\"namespace\":\"kafka\"},\"spec\":{\"authentication\":{\"type\":\"tls\"},\"authorization\":{\"acls\":[{\"operation\":\"All\",\"resource\":{\"name\":\"registry-schemas\",\"patternType\":\"literal\",\"type\":\"topic\"},\"type\":\"allow\"},{\"operation\":\"All\",\"resource\":{\"name\":\"schema-registry\",\"patternType\":\"prefix\",\"type\":\"group\"},\"type\":\"allow\"},{\"operation\":\"Describe\",\"resource\":{\"name\":\"__consumer_offsets\",\"patternType\":\"literal\",\"type\":\"topic\"},\"type\":\"allow\"}],\"type\":\"simple\"}}}\n"},"creationTimestamp":"2023-05-09T21:57:01Z","generation":1,"labels":{"strimzi.io/cluster":"my-cluster"},"managedFields":[{"apiVersion":"kafka.strimzi.io/v1beta2","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:strimzi.io/cluster":{}}},"f:spec":{".":{},"f:authentication":{".":{},"f:type":{}},"f:authorization":{".":{},"f:acls":{},"f:type":{}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2023-05-09T21:57:01Z"},{"apiVersion":"kafka.strimzi.io/v1beta2","fieldsType":"FieldsV1","fieldsV1":{"f:status":{".":{},"f:conditions":{},"f:observedGeneration":{}}},"manager":"strimzi-user-operator","operation":"Update","subresource":"status","time":"2023-05-09T21:58:10Z"}],"name":"confluent-schema-registry","namespace":"kafka","resourceVersion":"50364","uid":"366e5c0d-e804-464d-bd2f-5814e49ca921"},"spec":{"authentication":{"type":"tls"},"authorization":{"acls":[{"operation":"All","resource":{"name":"registry-schemas","patternType":"literal","type":"to
pic"},"type":"allow"},{"operation":"All","resource":{"name":"schema-registry","patternType":"prefix","type":"group"},"type":"allow"},{"operation":"Describe","resource":{"name":"__consumer_offsets","patternType":"literal","type":"topic"},"type":"allow"}],"type":"simple"}},"status":{"conditions":[{"lastTransitionTime":"2023-05-09T21:58:10.138163275Z","message":"io.strimzi.operator.common.ReconciliationException: io.strimzi.operator.cluster.model.InvalidResourceException: Simple authorization ACL rules are configured but not supported in the Kafka cluster configuration.","reason":"ExecutionException","status":"True","type":"NotReady"},{"lastTransitionTime":"2023-05-09T21:58:10.046348275Z","message":"In API version kafka.strimzi.io/v1beta2 the operation property at path spec.authorization.acls.operation has been deprecated, and should now be configured using spec.authorization.acls[*].operations.","reason":"DeprecatedFields","status":"True","type":"Warning"}],"observedGeneration":1}}

[2023-05-09 22:04:34,570] kubernetes.client.re [DEBUG   ] response body: {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"Kafka","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"kafka.strimzi.io/v1beta2\",\"kind\":\"Kafka\",\"metadata\":{\"annotations\":{},\"labels\":{\"skaffold.dev/run-id\":\"0271e368-f57e-4882-a9e7-15d77c6a5b38\"},\"name\":\"my-cluster\",\"namespace\":\"kafka\"},\"spec\":{\"entityOperator\":{\"topicOperator\":{},\"userOperator\":{}},\"kafka\":{\"config\":{\"default.replication.factor\":1,\"inter.broker.protocol.version\":\"3.4\",\"min.insync.replicas\":1,\"offsets.topic.replication.factor\":1,\"transaction.state.log.min.isr\":1,\"transaction.state.log.replication.factor\":1},\"listeners\":[{\"name\":\"plain\",\"port\":9092,\"tls\":false,\"type\":\"internal\"},{\"name\":\"tls\",\"port\":9093,\"tls\":true,\"type\":\"internal\"}],\"replicas\":1,\"storage\":{\"type\":\"ephemeral\"},\"version\":\"3.4.0\"},\"zookeeper\":{\"replicas\":3,\"storage\":{\"type\":\"ephemeral\"}}}}\n"},"creationTimestamp":"2023-05-09T21:57:01Z","generation":1,"labels":{"skaffold.dev/run-id":"0271e368-f57e-4882-a9e7-15d77c6a5b38"},"managedFields":[{"apiVersion":"kafka.strimzi.io/v1beta2","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:skaffold.dev/run-id":{}}},"f:spec":{".":{},"f:entityOperator":{".":{},"f:topicOperator":{},"f:userOperator":{}},"f:kafka":{".":{},"f:config":{".":{},"f:default.replication.factor":{},"f:inter.broker.protocol.version":{},"f:min.insync.replicas":{},"f:offsets.topic.replication.factor":{},"f:transaction.state.log.min.isr":{},"f:transaction.state.log.replication.factor":{}},"f:listeners":{},"f:replicas":{},"f:storage":{".":{},"f:type":{}},"f:version":{}},"f:zookeeper":{".":{},"f:replicas":{},"f:storage":{".":{},"f:type":{}}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2023-05-09T21:57:01Z"},{"
apiVersion":"kafka.strimzi.io/v1beta2","fieldsType":"FieldsV1","fieldsV1":{"f:status":{".":{},"f:clusterId":{},"f:conditions":{},"f:listeners":{},"f:observedGeneration":{}}},"manager":"strimzi-cluster-operator","operation":"Update","subresource":"status","time":"2023-05-09T21:58:27Z"}],"name":"my-cluster","namespace":"kafka","resourceVersion":"50398","uid":"4c6e0fe5-144a-48d8-a5df-a56f3c11d732"},"spec":{"entityOperator":{"topicOperator":{},"userOperator":{}},"kafka":{"config":{"default.replication.factor":1,"inter.broker.protocol.version":"3.4","min.insync.replicas":1,"offsets.topic.replication.factor":1,"transaction.state.log.min.isr":1,"transaction.state.log.replication.factor":1},"listeners":[{"name":"plain","port":9092,"tls":false,"type":"internal"},{"name":"tls","port":9093,"tls":true,"type":"internal"}],"replicas":1,"storage":{"type":"ephemeral"},"version":"3.4.0"},"zookeeper":{"replicas":3,"storage":{"type":"ephemeral"}}},"status":{"clusterId":"k3gEDCRaQ3C6j4IFOUK4FQ","conditions":[{"lastTransitionTime":"2023-05-09T21:57:31.682461275Z","message":"A Kafka cluster with a single replica and ephemeral storage will lose topic messages after any restart or rolling update.","reason":"KafkaStorage","status":"True","type":"Warning"},{"lastTransitionTime":"2023-05-09T21:58:27.855718275Z","status":"True","type":"Ready"}],"listeners":[{"addresses":[{"host":"my-cluster-kafka-bootstrap.kafka.svc","port":9092}],"bootstrapServers":"my-cluster-kafka-bootstrap.kafka.svc:9092","name":"plain","type":"plain"},{"addresses":[{"host":"my-cluster-kafka-bootstrap.kafka.svc","port":9093}],"bootstrapServers":"my-cluster-kafka-bootstrap.kafka.svc:9093","certificates":["-----BEGIN CERTIFICATE-----\nMIIFLTCCAxWgAwIBAgIUbY94tQI7UVourX/zrZMb0zoRDeQwDQYJKoZIhvcNAQEN\nBQAwLTETMBEGA1UECgwKaW8uc3RyaW16aTEWMBQGA1UEAwwNY2x1c3Rlci1jYSB2\nMDAeFw0yMzA1MDkyMTU3MDJaFw0yNDA1MDgyMTU3MDJaMC0xEzARBgNVBAoMCmlv\nLnN0cmltemkxFjAUBgNVBAMMDWNsdXN0ZXItY2EgdjAwggIiMA0GCSqGSIb3DQEB\nAQUAA4ICDwAwggIKAoICAQDALy3f77g6YGeWumyylwZMTsvcwkPNRp9UoHw7fniE\nOy85vbf+K9nDg
+OyDm9g8TgY1rx9SzEKe7FMcWufUp3gPjX1yrkmRBhKd4u5nAvJ\n5uTvkRfGDAxWqp943LIDtBYik2FXkgW8KIc0JbZyr2THfp/P/48f+/QRPUopyP3s\nIZXNNGL7Rk4Suo9yooUAhy9I2U2RhLNAJPkKmKH8tHTzc9YMzkZaDI5J4n81vRTC\nq1shIvbbe2KzjD5j8kfRLg0UAIzc3/seYjiNqchRWCVG7Zc6utbz3GKUzlL2IE3n\nZp6jAEsAgySsgm/PbHIEpWLqrtOKCY5OkbrwsZc0Kez0CAG9gGwdbvRhUmF0porC\nx4/h5Rf8NBL5qXlXawc3BHgNJ4yqJmJ3eROBKOsd6GteKgirugnj3blotfT8/5Qv\nBakTbQ04kplfVxDqkyb/OdpgpkIKNKzo/zhHjkB4ODrsiKdOS2Vhtgm4jaCOUIBn\nAVtDyKmM93N/0pVKZkoVkLbJT8WERF4w2dmTgE3tZk/JDtP4OrxNcW9Th+1XT8RD\nsu/Bn5m5lD8mxE8Wl9V7Ly0ej7czsk8IiVsXInWKFPMK0VGu6MkNzgsDCiMgP5h6\ner0vVNB+IwSvXPBM3SNvREN8AV5dxKEEx95vsPxi75rv+GO6gWmJmmAtG6FoOjoZ\n6wIDAQABo0UwQzAdBgNVHQ4EFgQUxKQACD3XfQuda9b+xFqp+KjroA4wEgYDVR0T\nAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQENBQADggIB\nAGTY6d5dBVZylLwaryQZRQeloXPhv8NxDue9+nfn6H5FKpJ/fCa6ZiRBY7HcG5SU\nxkxWsNiHQkKApRUjdUD5KC7n4AneMl7G5Ahg5hhtwxSwANTAa+byaz8WazVBx4K7\n59ZLEUFitT5bQajUIzllDU31ai8/Yb4fh+eSgPNKODaTnLbPPZjEI1pip37F13Oo\ngciV2p9YgLqkTs7a9zt7Tp07P8f+KEs3Q8/GYrQzKaFrkp8NAqqBf64CQbbHnsGd\nZzMA964d6SwFCNzvpedyYXAkV+EAfQkAPGdwnkjxGlkem9yI84GYq2jKZjig+d9q\nHQ7rA1goHidHOKDg6qy5kPN4+92sK6GR08AfpyUIcObhGzPNgBjnKA94kGKhffiq\nm3sb8n5Z0AtcjGfxo/AIrDtt6yk2S3yfbuDMirKlsZk6t9FeKMIB+zHYKZ5PvM6v\n+0VN0SgUvZ38tDFoOjdF8BFaUtCZiiL+o/5L5bJm6Iio/RNR703Gs/pvXjbQjAtO\nH1JV4Q5WOIQgrMAv/OkCW37yUeclHC1wBiXfQDxrP4ElPISkle04We9y6F02HW6t\nIzDNf8P0kfpsEm+yVCVkjKqIt8MrKkOZROHtg/yjmJfBDfmB1lnaB+141KmZfPWk\n9dQKjsVvAENFV3O6qCsnm59qIhbchdaq6Efy3+EFHF7w\n-----END CERTIFICATE-----\n"],"name":"tls","type":"tls"}],"observedGeneration":1}}
2023-05-09T22:04:34.572555275Z 
[2023-05-09 22:04:34,589] kopf.objects         [INFO    ] [kafka/confluent-schema-registry] Retrieved cluster CA certificate
[2023-05-09 22:04:34,592] kopf.objects         [INFO    ] [kafka/confluent-schema-registry] Cluster CA certificate version: 50095
[2023-05-09 22:04:34,626] kopf.objects         [ERROR   ] [kafka/confluent-schema-registry] Handler 'create_registry' failed with an exception. Will retry.
2023-05-09T22:04:34.628674275Z Traceback (most recent call last):
2023-05-09T22:04:34.628721275Z   File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
2023-05-09T22:04:34.628796275Z   File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
2023-05-09T22:04:34.628831275Z     result = await invocation.invoke(
  File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke
2023-05-09T22:04:34.628901275Z     await asyncio.shield(future)  # slightly expensive: creates tasks
2023-05-09T22:04:34.628939275Z   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/strimziregistryoperator/handlers/createregistry.py", line 136, in create_registry
    secret = create_secret(
  File "/opt/venv/lib/python3.10/site-packages/strimziregistryoperator/certprocessor.py", line 76, in create_secret
    client_secret = get_secret(
  File "/opt/venv/lib/python3.10/site-packages/strimziregistryoperator/k8s.py", line 120, in get_secret
2023-05-09T22:04:34.629193275Z     result = api.read_namespaced_secret(
2023-05-09T22:04:34.629481275Z   File "/opt/venv/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 24803, in read_namespaced_secret
2023-05-09T22:04:34.629596275Z     return self.read_namespaced_secret_with_http_info(name, namespace, **kwargs)  # noqa: E501
2023-05-09T22:04:34.629671275Z   File "/opt/venv/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 24890, in read_namespaced_secret_with_http_info
2023-05-09T22:04:34.629783275Z     return self.api_client.call_api(
  File "/opt/venv/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in call_api
2023-05-09T22:04:34.629928275Z     return self.__call_api(resource_path, method,
2023-05-09T22:04:34.629979275Z   File "/opt/venv/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
2023-05-09T22:04:34.630036275Z     response_data = self.request(
2023-05-09T22:04:34.630150275Z   File "/opt/venv/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 373, in request
2023-05-09T22:04:34.630216275Z     return self.rest_client.GET(url,
  File "/opt/venv/lib/python3.10/site-packages/kubernetes/client/rest.py", line 240, in GET
2023-05-09T22:04:34.630293275Z     return self.request("GET", url,
2023-05-09T22:04:34.630327275Z   File "/opt/venv/lib/python3.10/site-packages/kubernetes/client/rest.py", line 234, in request
2023-05-09T22:04:34.630362275Z     raise ApiException(http_resp=r)
2023-05-09T22:04:34.630401275Z kubernetes.client.exceptions.ApiException: (404)
2023-05-09T22:04:34.630436275Z Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ce079e4b-5895-46d4-a64b-281554396d8f', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'dc0327c8-640d-4099-9826-fd4709b6d952', 'X-Kubernetes-Pf-Prioritylevel-Uid': '52a754a4-bd10-4e90-ba33-04ea09f638b7', 'Date': 'Tue, 09 May 2023 22:04:34 GMT', 'Content-Length': '224'})
2023-05-09T22:04:34.630508275Z HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \\"confluent-schema-registry\\" not found","reason":"NotFound","details":{"name":"confluent-schema-registry","kind":"secrets"},"code":404}\n'
2023-05-09T22:04:34.630541275Z 
2023-05-09T22:04:34.631328275Z [2023-05-09 22:04:34,628] kopf.objects         [DEBUG   ] [kafka/confluent-schema-registry] Patching with: {'metadata': {'annotations': {'kopf.zalando.org/create_registry': '{"started":"2023-05-09T21:05:22.061647","delayed":"2023-05-09T22:05:34.627706","purpose":"create","retries":74,"success":false,"failure":false,"message":"(404)\\nReason: Not Found\\nHTTP response headers: HTTPHeaderDict({\'Audit-Id\': \'ce079e4b-5895-46d4-a64b-281554396d8f\', \'Cache-Control\': \'no-cache, private\', \'Content-Type\': \'application/json\', \'X-Kubernetes-Pf-Flowschema-Uid\': \'dc0327c8-640d-4099-9826-fd4709b6d952\', \'X-Kubernetes-Pf-Prioritylevel-Uid\': \'52a754a4-bd10-4e90-ba33-04ea09f638b7\', \'Date\': \'Tue, 09 May 2023 22:04:34 GMT\', \'Content-Length\': \'224\'})\\nHTTP response body: b\'{\\"kind\\":\\"Status\\",\\"apiVersion\\":\\"v1\\",\\"metadata\\":{},\\"status\\":\\"Failure\\",\\"message\\":\\"secrets \\\\\\\\\\"confluent-schema-registry\\\\\\\\\\" not found\\",\\"reason\\":\\"NotFound\\",\\"details\\":{\\"name\\":\\"confluent-schema-registry\\",\\"kind\\":\\"secrets\\"},\\"code\\":404}\\\\n\'\\n"}', 'kopf.zalando.org/touch-dummy': None}}, 'status': {'kopf': {'progress': {'create_registry': {'started': '2023-05-09T21:05:22.061647', 'stopped': None, 'delayed': '2023-05-09
T22:05:34.627706', 'purpose': 'create', 'retries': 74, 'success': False, 'failure': False, 'message': '(404)\nReason: Not Found\nHTTP response headers: HTTPHeaderDict({\'Audit-Id\': \'ce079e4b-5895-46d4-a64b-281554396d8f\', \'Cache-Control\': \'no-cache, private\', \'Content-Type\': \'application/json\', \'X-Kubernetes-Pf-Flowschema-Uid\': \'dc0327c8-640d-4099-9826-fd4709b6d952\', \'X-Kubernetes-Pf-Prioritylevel-Uid\': \'52a754a4-bd10-4e90-ba33-04ea09f638b7\', \'Date\': \'Tue, 09 May 2023 22:04:34 GMT\', \'Content-Length\': \'224\'})\nHTTP response body: b\'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \\\\"confluent-schema-registry\\\\" not found","reason":"NotFound","details":{"name":"confluent-schema-registry","kind":"secrets"},"code":404}\\n\'\n', 'subrefs': None}}}}}
[2023-05-09 22:04:34,666] kopf.objects         [WARNING ] [kafka/confluent-schema-registry] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'create_registry': {'started': '2023-05-09T21:05:22.061647', 'stopped': None, 'delayed': '2023-05-09T22:05:34.627706', 'purpose': 'create', 'retries': 74, 'success': False, 'failure': False, 'message': '(404)\nReason: Not Found\nHTTP response headers: HTTPHeaderDict({\'Audit-Id\': \'ce079e4b-5895-46d4-a64b-281554396d8f\', \'Cache-Control\': \'no-cache, private\', \'Content-Type\': \'application/json\', \'X-Kubernetes-Pf-Flowschema-Uid\': \'dc0327c8-640d-4099-9826-fd4709b6d952\', \'X-Kubernetes-Pf-Prioritylevel-Uid\': \'52a754a4-bd10-4e90-ba33-04ea09f638b7\', \'Date\': \'Tue, 09 May 2023 22:04:34 GMT\', \'Content-Length\': \'224\'})\nHTTP response body: b\'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \\\\"confluent-schema-registry\\\\" not found","reason":"NotFound","details":{"name":"confluent-schema-registry","kind":"secrets"},"code":404}\\n\'\n', 'subrefs': None}}}}, None),)
2023-05-09T22:04:34.667028275Z [2023-05-09 22:04:34,666] kopf.objects         [DEBUG   ] [kafka/confluent-schema-registry] Sleeping was skipped because of the patch, 59.999783 seconds left.
[2023-05-09 22:04:34,770] kopf.objects         [DEBUG   ] [kafka/confluent-schema-registry] Creation is in progress: {'apiVersion': 'roundtable.lsst.codes/v1beta1', 'kind': 'StrimziSchemaRegistry', 'metadata': {'annotations': {'kopf.zalando.org/create_registry': '{"started":"2023-05-09T21:05:22.061647","delayed":"2023-05-09T22:05:34.627706","purpose":"create","retries":74,"success":false,"failure":false,"message":"(404)\\nReason: Not Found\\nHTTP response headers: HTTPHeaderDict({\'Audit-Id\': \'ce079e4b-5895-46d4-a64b-281554396d8f\', \'Cache-Control\': \'no-cache, private\', \'Content-Type\': \'application/json\', \'X-Kubernetes-Pf-Flowschema-Uid\': \'dc0327c8-640d-4099-9826-fd4709b6d952\', \'X-Kubernetes-Pf-Prioritylevel-Uid\': \'52a754a4-bd10-4e90-ba33-04ea09f638b7\', \'Date\': \'Tue, 09 May 2023 22:04:34 GMT\', \'Content-Length\': \'224\'})\\nHTTP response body: b\'{\\"kind\\":\\"Status\\",\\"apiVersion\\":\\"v1\\",\\"metadata\\":{},\\"status\\":\\"Failure\\",\\"message\\":\\"secrets \\\\\\\\\\"confluent-schema-registry\\\\\\\\\\" not found\\",\\"reason\\":\\"NotFound\\",\\"details\\":{\\"name\\":\\"confluent-schema-registry\\",\\"kind\\":\\"secrets\\"},\\"code\\":404}\\\\n\'\\n"}', 'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"roundtable.lsst.codes/v1beta1","kind":"StrimziSchemaRegistry","metadata":{"annotations":{},"name":"confluent-schema-registry","namespace":"kafka"},"spec":{"compatibilityLevel":"forward","listener":"tls","securityProtocol":"PLAINTEXT","strimziVersion":"v1beta2"}}\n'}, 'creationTimestamp': '2023-05-09T21:05:21Z', 'generation': 5, 'managedFields': [{'apiVersion': 'roundtable.lsst.codes/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:compatibilityLevel': {}, 'f:cpuLimit': {}, 'f:cpuRequest': {}, 'f:listener': {}, 'f:memoryLimit': {}, 'f:memoryRequest': {}, 'f:registryImage': {}, 'f:registryImageTag': {}, 'f:securi
tyProtocol': {}, 'f:serviceType': {}, 'f:strimzi-version': {}, 'f:strimziVersion': {}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2023-05-09T22:03:58Z'}, {'apiVersion': 'roundtable.lsst.codes/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'f:kopf.zalando.org/create_registry': {}}}}, 'manager': 'kopf', 'operation': 'Update', 'time': '2023-05-09T22:04:34Z'}], 'name': 'confluent-schema-registry', 'namespace': 'kafka', 'resourceVersion': '50820', 'uid': 'fd9c7949-1c48-44a7-9b69-2facc4d8df69'}, 'spec': {'compatibilityLevel': 'forward', 'cpuLimit': '', 'cpuRequest': '', 'listener': 'tls', 'memoryLimit': '', 'memoryRequest': '', 'registryImage': 'confluentinc/cp-schema-registry', 'registryImageTag': '7.2.1', 'securityProtocol': 'PLAINTEXT', 'serviceType': 'ClusterIP', 'strimzi-version': 'v1beta2', 'strimziVersion': 'v1beta2'}}
2023-05-09T22:04:34.772572275Z [2023-05-09 22:04:34,771] kopf.objects         [DEBUG   ] [kafka/confluent-schema-registry] Sleeping for 59.856435 seconds for the delayed handlers.
```

**Comment by pvannierop** [comment]
I experience the same on v0.6.0

**Comment by pvannierop** [comment]
Followup: I was able to fix following [this](https://github.com/lsst-sqre/strimzi-registry-operator/issues/77#issuecomment-1282276802) pointer. In short, the authorization method for the KafkaUser was _simple_ which should be also allowed by the Kafka cluster.
