### ISSUE TITLE
Operator permission issues

### ISSUE THREAD

**Issue by Impulse87** [lsst-sqre/strimzi-registry-operator#22]
Hello, i'm trying to get the operator working on a GCP cluster with a working strimzi-kafka stack. The strimzi-kafka stack is deployed to a namespace called "kafka". The strimzi-registry-operator deployment was also done into this namespace. 

A double check of the serviceaccount + role + rolebinding on the cluster seems good too. But the operator is crashing with following log entries:
```
[2022-03-15 08:41:12,267] kopf.clients.auth    [DEBUG   ] Pykube is configured in cluster with service account.
[2022-03-15 08:41:12,285] kopf.clients.auth    [DEBUG   ] Client is configured in cluster with service account.
[2022-03-15 08:41:12,357] kopf.reactor.running [ERROR   ] Root task 'watcher of secrets.' is failed: HTTPError('403 Client Error: Forbidden for url: https://10.0.128.1:443/api/v1/namespaces/events/secrets')
[2022-03-15 08:41:12,357] kopf.reactor.running [ERROR   ] Root task 'watcher of strimzischemaregistries.roundtable.lsst.codes' is failed: HTTPError('403 Client Error: Forbidden for url: https://10.0.128.1:443/apis/roundtable.lsst.codes/v1beta1/namespaces/events/strimzischemaregistries')
[2022-03-15 08:41:12,357] kopf.reactor.running [DEBUG   ] Root task 'poster of events' is cancelled.
[2022-03-15 08:41:12,357] kopf.reactor.running [DEBUG   ] Root tasks are stopped: finished normally; tasks left: set()
[2022-03-15 08:41:12,358] kopf.reactor.running [DEBUG   ] Hung tasks stopping is skipped: no tasks given.
Traceback (most recent call last):
  File "/opt/venv/bin/kopf", line 8, in <module>
Exception when calling CustomObjectsApi->list_namespaced_custom_object: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'a33c5c91-5d93-46d6-ac7d-5496a87dfa59', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '474e4962-5d35-4d9c-9f49-981defbbe192', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'c36a8cd5-1ce3-464c-a153-99b73e582954', 'Date': 'Tue, 15 Mar 2022 08:41:12 GMT', 'Content-Length': '429'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"strimzischemaregistries.roundtable.lsst.codes is forbidden: User \"system:serviceaccount:kafka:strimzi-registry-operator\" cannot list resource \"strimzischemaregistries\" in API group \"roundtable.lsst.codes\" in the namespace \"events\"","reason":"Forbidden","details":{"group":"roundtable.lsst.codes","kind":"strimzischemaregistries"},"code":403}



    sys.exit(main())
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/kopf/cli.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/kopf/cli.py", line 59, in run
    return running.run(
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 38, in run
    loop.run_until_complete(operator(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 79, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 215, in run_tasks
    await _reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 263, in _reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 270, in _root_task_checker
    await coro
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/queueing.py", line 80, in watcher
    async for event in watching.infinite_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 86, in infinite_watch
    async for event in streaming_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 101, in streaming_watch
    rsp = fetching.list_objs(resource=resource, namespace=namespace)
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/fetching.py", line 61, in list_objs
    return lst.response
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 199, in response
    return self.query_cache["response"]
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 185, in query_cache
    cache["response"] = self.execute().json()
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 160, in execute
    r.raise_for_status()
  File "/opt/venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.0.128.1:443/apis/roundtable.lsst.codes/v1beta1/namespaces/events/strimzischemaregistries
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<_root_task_checker() done, defined at /opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py:268> exception=HTTPError('403 Client Error: Forbidden for url: https://10.0.128.1:443/api/v1/namespaces/events/secrets')>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 270, in _root_task_checker
    await coro
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/queueing.py", line 80, in watcher
    async for event in watching.infinite_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 86, in infinite_watch
    async for event in streaming_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 101, in streaming_watch
    rsp = fetching.list_objs(resource=resource, namespace=namespace)
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/fetching.py", line 61, in list_objs
    return lst.response
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 199, in response
    return self.query_cache["response"]
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 185, in query_cache
    cache["response"] = self.execute().json()
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 160, in execute
    r.raise_for_status()
  File "/opt/venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.0.128.1:443/api/v1/namespaces/events/secrets
[2022-03-15 08:42:36,404] kopf.clients.auth    [DEBUG   ] Pykube is configured in cluster with service account.
[2022-03-15 08:42:36,430] kopf.clients.auth    [DEBUG   ] Client is configured in cluster with service account.
[2022-03-15 08:42:36,515] kopf.reactor.running [ERROR   ] Root task 'watcher of secrets.' is failed: HTTPError('403 Client Error: Forbidden for url: https://10.0.128.1:443/api/v1/namespaces/events/secrets')
[2022-03-15 08:42:36,515] kopf.reactor.running [ERROR   ] Root task 'watcher of strimzischemaregistries.roundtable.lsst.codes' is failed: HTTPError('403 Client Error: Forbidden for url: https://10.0.128.1:443/apis/roundtable.lsst.codes/v1beta1/namespaces/events/strimzischemaregistries')
[2022-03-15 08:42:36,515] kopf.reactor.running [DEBUG   ] Root task 'poster of events' is cancelled.
[2022-03-15 08:42:36,515] kopf.reactor.running [DEBUG   ] Root tasks are stopped: finished normally; tasks left: set()
[2022-03-15 08:42:36,516] kopf.reactor.running [DEBUG   ] Hung tasks stopping is skipped: no tasks given.
Traceback (most recent call last):
  File "/opt/venv/bin/kopf", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/kopf/cli.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/kopf/cli.py", line 59, in run
    return running.run(
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 38, in run
    loop.run_until_complete(operator(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 79, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 215, in run_tasks
    await _reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 263, in _reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 270, in _root_task_checker
    await coro
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/queueing.py", line 80, in watcher
    async for event in watching.infinite_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 86, in infinite_watch
    async for event in streaming_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 101, in streaming_watch
    rsp = fetching.list_objs(resource=resource, namespace=namespace)
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/fetching.py", line 61, in list_objs
    return lst.response
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 199, in response
    return self.query_cache["response"]
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 185, in query_cache
    cache["response"] = self.execute().json()
Exception when calling CustomObjectsApi->list_namespaced_custom_object: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '16019b00-e514-4b0a-9e5e-b69df742ffc0', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '474e4962-5d35-4d9c-9f49-981defbbe192', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'c36a8cd5-1ce3-464c-a153-99b73e582954', 'Date': 'Tue, 15 Mar 2022 08:42:36 GMT', 'Content-Length': '429'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"strimzischemaregistries.roundtable.lsst.codes is forbidden: User \"system:serviceaccount:kafka:strimzi-registry-operator\" cannot list resource \"strimzischemaregistries\" in API group \"roundtable.lsst.codes\" in the namespace \"events\"","reason":"Forbidden","details":{"group":"roundtable.lsst.codes","kind":"strimzischemaregistries"},"code":403}



  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 160, in execute
    r.raise_for_status()
  File "/opt/venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.0.128.1:443/apis/roundtable.lsst.codes/v1beta1/namespaces/events/strimzischemaregistries
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<_root_task_checker() done, defined at /opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py:268> exception=HTTPError('403 Client Error: Forbidden for url: https://10.0.128.1:443/api/v1/namespaces/events/secrets')>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 270, in _root_task_checker
    await coro
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/queueing.py", line 80, in watcher
    async for event in watching.infinite_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 86, in infinite_watch
    async for event in streaming_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 101, in streaming_watch
    rsp = fetching.list_objs(resource=resource, namespace=namespace)
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/fetching.py", line 61, in list_objs
    return lst.response
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 199, in response
    return self.query_cache["response"]
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 185, in query_cache
    cache["response"] = self.execute().json()
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 160, in execute
    r.raise_for_status()
  File "/opt/venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.0.128.1:443/api/v1/namespaces/events/secrets
[2022-03-15 08:45:20,372] kopf.clients.auth    [DEBUG   ] Pykube is configured in cluster with service account.
[2022-03-15 08:45:20,398] kopf.clients.auth    [DEBUG   ] Client is configured in cluster with service account.
[2022-03-15 08:45:20,499] kopf.reactor.running [ERROR   ] Root task 'watcher of strimzischemaregistries.roundtable.lsst.codes' is failed: HTTPError('403 Client Error: Forbidden for url: https://10.0.128.1:443/apis/roundtable.lsst.codes/v1beta1/namespaces/events/strimzischemaregistries')
[2022-03-15 08:45:20,500] kopf.reactor.running [ERROR   ] Root task 'watcher of secrets.' is failed: HTTPError('403 Client Error: Forbidden for url: https://10.0.128.1:443/api/v1/namespaces/events/secrets')
[2022-03-15 08:45:20,502] kopf.reactor.running [DEBUG   ] Root task 'poster of events' is cancelled.
[2022-03-15 08:45:20,503] kopf.reactor.running [DEBUG   ] Root tasks are stopped: finished normally; tasks left: set()
[2022-03-15 08:45:20,503] kopf.reactor.running [DEBUG   ] Hung tasks stopping is skipped: no tasks given.
Traceback (most recent call last):
  File "/opt/venv/bin/kopf", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
Exception when calling CustomObjectsApi->list_namespaced_custom_object: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '66a9ffc1-87b5-420f-be78-762e90f71b1e', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '474e4962-5d35-4d9c-9f49-981defbbe192', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'c36a8cd5-1ce3-464c-a153-99b73e582954', 'Date': 'Tue, 15 Mar 2022 08:45:20 GMT', 'Content-Length': '429'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"strimzischemaregistries.roundtable.lsst.codes is forbidden: User \"system:serviceaccount:kafka:strimzi-registry-operator\" cannot list resource \"strimzischemaregistries\" in API group \"roundtable.lsst.codes\" in the namespace \"events\"","reason":"Forbidden","details":{"group":"roundtable.lsst.codes","kind":"strimzischemaregistries"},"code":403}


2022-03-15T08:45:20.504821534Z
[2022-03-15 08:50:30,195] kopf.clients.auth    [DEBUG   ] Pykube is configured in cluster with service account.
[2022-03-15 08:50:30,222] kopf.clients.auth    [DEBUG   ] Client is configured in cluster with service account.
[2022-03-15 08:50:30,300] kopf.reactor.running [ERROR   ] Root task 'watcher of secrets.' is failed: HTTPError('403 Client Error: Forbidden for url: https://10.0.128.1:443/api/v1/namespaces/events/secrets')
[2022-03-15 08:50:30,300] kopf.reactor.running [ERROR   ] Root task 'watcher of strimzischemaregistries.roundtable.lsst.codes' is failed: HTTPError('403 Client Error: Forbidden for url: https://10.0.128.1:443/apis/roundtable.lsst.codes/v1beta1/namespaces/events/strimzischemaregistries')
[2022-03-15 08:50:30,301] kopf.reactor.running [DEBUG   ] Root task 'poster of events' is cancelled.
[2022-03-15 08:50:30,301] kopf.reactor.running [DEBUG   ] Root tasks are stopped: finished normally; tasks left: set()
[2022-03-15 08:50:30,301] kopf.reactor.running [DEBUG   ] Hung tasks stopping is skipped: no tasks given.
Traceback (most recent call last):
  File "/opt/venv/bin/kopf", line 8, in <module>
Exception when calling CustomObjectsApi->list_namespaced_custom_object: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ebeff016-e820-4ff0-b95a-c4265d4af1ed', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '474e4962-5d35-4d9c-9f49-981defbbe192', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'c36a8cd5-1ce3-464c-a153-99b73e582954', 'Date': 'Tue, 15 Mar 2022 08:50:30 GMT', 'Content-Length': '429'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"strimzischemaregistries.roundtable.lsst.codes is forbidden: User \"system:serviceaccount:kafka:strimzi-registry-operator\" cannot list resource \"strimzischemaregistries\" in API group \"roundtable.lsst.codes\" in the namespace \"events\"","reason":"Forbidden","details":{"group":"roundtable.lsst.codes","kind":"strimzischemaregistries"},"code":403}



    sys.exit(main())
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/kopf/cli.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/kopf/cli.py", line 59, in run
    return running.run(
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 38, in run
    loop.run_until_complete(operator(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 79, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 215, in run_tasks
    await _reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 263, in _reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 270, in _root_task_checker
    await coro
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/queueing.py", line 80, in watcher
    async for event in watching.infinite_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 86, in infinite_watch
    async for event in streaming_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 101, in streaming_watch
    rsp = fetching.list_objs(resource=resource, namespace=namespace)
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/fetching.py", line 61, in list_objs
    return lst.response
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 199, in response
    return self.query_cache["response"]
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 185, in query_cache
    cache["response"] = self.execute().json()
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 160, in execute
    r.raise_for_status()
  File "/opt/venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.0.128.1:443/apis/roundtable.lsst.codes/v1beta1/namespaces/events/strimzischemaregistries
```

This is the deployed serviceaccount:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-registry-operator
  namespace: kafka
  uid: 2243433a-b873-4a1f-b5b0-6da27684b9f3
  resourceVersion: '55436239'
  creationTimestamp: '2022-03-15T08:38:54Z'
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lis-kafka-schema-registry-operator-test
    meta.helm.sh/release-namespace: kafka
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: v1
      time: '2022-03-15T08:38:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-03-15T08:38:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:secrets:
          .: {}
          k:{"name":"strimzi-registry-operator-token-m9wm9"}:
            .: {}
            f:name: {}
  selfLink: /api/v1/namespaces/kafka/serviceaccounts/strimzi-registry-operator
secrets:
  - name: strimzi-registry-operator-token-m9wm9

```

This is the deployed role:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: strimzi-registry-operator
  namespace: kafka
  uid: 452026eb-6fef-436e-ae67-ba8deb7f1115
  resourceVersion: '55436243'
  creationTimestamp: '2022-03-15T08:38:54Z'
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lis-kafka-schema-registry-operator-test
    meta.helm.sh/release-namespace: kafka
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2022-03-15T08:38:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:rules: {}
  selfLink: >-
    /apis/rbac.authorization.k8s.io/v1/namespaces/kafka/roles/strimzi-registry-operator
rules:
  - verbs:
      - list
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - create
    apiGroups:
      - events.k8s.io
    resources:
      - events
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - roundtable.lsst.codes
    resources:
      - strimzischemaregistries
  - verbs:
      - get
      - list
      - watch
      - patch
      - create
    apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
      - services
  - verbs:
      - get
      - list
      - watch
      - patch
      - create
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - list
      - get
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkausers
      - kafkas

```

And this is the deployed rolebinding:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-registry-operator
  namespace: kafka
  uid: 1c8608ea-4f9c-4ec0-93c2-2fc44f1793c2
  resourceVersion: '55436244'
  creationTimestamp: '2022-03-15T08:38:54Z'
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lis-kafka-schema-registry-operator-test
    meta.helm.sh/release-namespace: kafka
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2022-03-15T08:38:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:roleRef:
          f:apiGroup: {}
          f:kind: {}
          f:name: {}
        f:subjects: {}
  selfLink: >-
    /apis/rbac.authorization.k8s.io/v1/namespaces/kafka/rolebindings/strimzi-registry-operator
subjects:
  - kind: ServiceAccount
    name: strimzi-registry-operator
    namespace: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: strimzi-registry-operator

```

This is the operator deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-registry-operator
  namespace: kafka
  uid: 731f63f7-5994-43ef-ab15-314c096377eb
  resourceVersion: '55444469'
  generation: 1
  creationTimestamp: '2022-03-15T08:38:54Z'
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: lis-kafka-schema-registry-operator-test
    meta.helm.sh/release-namespace: kafka
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: apps/v1
      time: '2022-03-15T08:38:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"operator"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:serviceAccount: {}
              f:serviceAccountName: {}
              f:terminationGracePeriodSeconds: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-03-15T09:00:49Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:replicas: {}
          f:unavailableReplicas: {}
          f:updatedReplicas: {}
  selfLink: /apis/apps/v1/namespaces/kafka/deployments/strimzi-registry-operator
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-03-15T08:39:24Z'
      lastTransitionTime: '2022-03-15T08:38:55Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "strimzi-registry-operator-7fb5f7db9c" has successfully
        progressed.
    - type: Available
      status: 'False'
      lastUpdateTime: '2022-03-15T09:00:49Z'
      lastTransitionTime: '2022-03-15T09:00:49Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strimzi-registry-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strimzi-registry-operator
    spec:
      containers:
        - name: operator
          image: lsstsqre/strimzi-registry-operator:0.4.1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: strimzi-registry-operator
      serviceAccount: strimzi-registry-operator
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

```

As for the Kafka Topic and User, the example from the readme was deployed after operator deployment.

**Comment by Impulse87** [comment]
ok already found the solution... kafka cluster name and namespace needs to be given in the operator deployment as env vars. Like so:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.namespaceOverride }}
spec:
  replicas: 1  # do not change to >1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name }}
    spec:
      serviceAccountName: {{ .Values.metadata.name }}
      containers:
        - name: operator
          image: '{{ .Values.image }}'
          imagePullPolicy: Always
          env:
            - name: SSR_CLUSTER_NAME
              value: "{{ .Values.kafka.strimziCluster }}"
            - name: SSR_NAMESPACE
              value: "{{ .Values.namespaceOverride }}"

```
