### ISSUE TITLE
Schema Registry Failed to create

### ISSUE THREAD

**Issue by Sai-Charan-Madhvaraj** [lsst-sqre/strimzi-registry-operator#37]
Hi Team, 

We are getting below error when we are trying to apply kind: StrimziSchemaRegistry

used these environment variables in schema registry operator deployment 

``` 
        env:
            - name: SSR_CLUSTER_NAME
              value: "cdt-west-1-shared-emp-kafka"
            - name: SSR_NAMESPACE
              value: "emp-kafka"
  ``` 

``` 
[2022-05-16 14:36:03,617] kopf.objects         [DEBUG   ] [emp-kafka/confluent-schema-registry] Invoking handler 'handle_secret_change'.
[2022-05-16 14:36:03,617] kopf.objects         [INFO    ] [emp-kafka/confluent-schema-registry] Handler 'handle_secret_change' succeeded.


[2022-05-16 14:37:30,886] kopf.reactor.running [ERROR   ] Root task 'watcher of strimzischemaregistries.roundtable.lsst.codes' is failed: ChunkedEncodingError(ProtocolError("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer')))
[2022-05-16 14:37:30,886] kopf.reactor.running [DEBUG   ] Root task 'poster of events' is cancelled.
[2022-05-16 14:37:30,886] kopf.reactor.running [DEBUG   ] Root task 'watcher of secrets.' is cancelled.
[2022-05-16 14:37:30,886] kopf.reactor.running [DEBUG   ] Root tasks are stopped: finished normally; tasks left: set()
[2022-05-16 14:37:30,886] kopf.reactor.running [DEBUG   ] Hung tasks stopping is skipped: no tasks given.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/opt/venv/lib/python3.9/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/opt/venv/lib/python3.9/site-packages/urllib3/response.py", line 694, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/requests/models.py", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/opt/venv/lib/python3.9/site-packages/urllib3/response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/opt/venv/lib/python3.9/site-packages/urllib3/response.py", line 793, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/venv/lib/python3.9/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/bin/kopf", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/kopf/cli.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/kopf/cli.py", line 59, in run
    return running.run(
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 38, in run
    loop.run_until_complete(operator(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 79, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 215, in run_tasks
    await _reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 263, in _reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/running.py", line 270, in _root_task_checker
    await coro
  File "/opt/venv/lib/python3.9/site-packages/kopf/reactor/queueing.py", line 80, in watcher
    async for event in watching.infinite_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 86, in infinite_watch
    async for event in streaming_watch(resource=resource, namespace=namespace):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 114, in streaming_watch
    async for event in streaming_aiter(stream, loop=loop):
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 66, in streaming_aiter
    yield await loop.run_in_executor(executor, streaming_next, src)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 54, in streaming_next
    return next(src)
  File "/opt/venv/lib/python3.9/site-packages/kopf/clients/watching.py", line 159, in <genexpr>
    return iter({'type': event.type, 'object': event.object.obj} for event in src)
  File "/opt/venv/lib/python3.9/site-packages/pykube/query.py", line 223, in object_stream
    for line in r.iter_lines():
  File "/opt/venv/lib/python3.9/site-packages/requests/models.py", line 804, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/opt/venv/lib/python3.9/site-packages/requests/models.py", line 763, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

```

**Comment by jonathansick** [comment]
@Sai-Charan-Madhvaraj take a look at version 0.5.0 of the operator. We've cleaned up how we handle Kafka listeners and the security protocol, which might resolve your issue.

Specifically, `listener` now refers to the *name* of the listener in the Kafka resource. And the securityProtocol will also let you select either plaintext or SSL. See https://github.com/lsst-sqre/strimzi-registry-operator#schema-registry-related-configurations for details.
