### ISSUE TITLE
Error in CreateRegistry

### ISSUE THREAD

**Issue by bkak** [lsst-sqre/strimzi-registry-operator#84]
I am deploying this operator in AKS using tls.

However, upon starting "StrimziSchemaRegistry" I get this error in registry operator -

```2022-11-23 15:47:42,760] kopf.objects         [ERROR   ] [tls-kafka/confluent-schema-registry] Handler 'create_registry' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
  File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
    result = await invocation.invoke(
  File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/strimziregistryoperator/handlers/createregistry.py", line 131, in create_registry
    bootstrap_server = get_kafka_bootstrap_server(
  File "/opt/venv/lib/python3.10/site-packages/strimziregistryoperator/deployments.py", line 83, in get_kafka_bootstrap_server
    raise kopf.Error(msg, delay=10)
AttributeError: module 'kopf' has no attribute 'Error'
[2022-11-23 15:47:42,760] kopf.objects         [DEBUG   ] [tls-kafka/confluent-schema-registry] Patching with: {'metadata': {'annotations': {'kopf.zalando.org/create_registry': '{"started":"2022-11-23T08:18:50.979989","delayed":"2022-11-23T15:48:42.760410","purpose":"create","retries":438,"success":false,"failure":false,"message":"module \'kopf\' has no attribute \'Error\'"}', 'kopf.zalando.org/touch-dummy': None}}, 'status': {'kopf': {'progress': {'create_registry': {'started': '2022-11-23T08:18:50.979989', 'stopped': None, 'delayed': '2022-11-23T15:48:42.760410', 'purpose': 'create', 'retries': 438, 'success': False, 'failure': False, 'message': "module 'kopf' has no attribute 'Error'", 'subrefs': None}}}}}
[2022-11-23 15:47:42,788] kopf.objects         [WARNING ] [tls-kafka/confluent-schema-registry] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'create_registry': {'started': '2022-11-23T08:18:50.979989', 'stopped': None, 'delayed': '2022-11-23T15:48:42.760410', 'purpose': 'create', 'retries': 438, 'success': False, 'failure': False, 'message': "module 'kopf' has no attribute 'Error'", 'subrefs': None}}}}, None),)
[2022-11-23 15:47:42,788] kopf.objects         [DEBUG   ] [tls-kafka/confluent-schema-registry] Sleeping was skipped because of the patch, 59.999766 seconds left.
```

Using this manifest for StrimziSchemaRegistry
```
apiVersion: roundtable.lsst.codes/v1beta1
kind: StrimziSchemaRegistry
metadata:
  name: confluent-schema-registry
spec:
  strimziVersion: v1beta2
  listener: tls
  securityProtocol: tls
  compatibilityLevel: forward
  registryImage: confluentinc/cp-schema-registry
  registryImageTag: "7.2.2"  
  cpuLimit: ""
  cpuRequest: ""
  memoryLimit: ""
  memoryRequest: ""
```
I am stuck now, with no idea where to debug. Any help is appreciated.

**Comment by karanalang** [comment]
I'm having similar issue .. @bkak  - did you find a fix for this ?

Note : I'm deploying on GKE (Kubernetes), though i think that should not make a difference

**Comment by karanalang** [comment]
> I am deploying this operator in AKS using tls.
> 
> However, upon starting "StrimziSchemaRegistry" I get this error in registry operator -
> 
> ```
> Traceback (most recent call last):
>   File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
>     result = await invoke_handler(
>   File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
>     result = await invocation.invoke(
>   File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke
>     await asyncio.shield(future)  # slightly expensive: creates tasks
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/opt/venv/lib/python3.10/site-packages/strimziregistryoperator/handlers/createregistry.py", line 131, in create_registry
>     bootstrap_server = get_kafka_bootstrap_server(
>   File "/opt/venv/lib/python3.10/site-packages/strimziregistryoperator/deployments.py", line 83, in get_kafka_bootstrap_server
>     raise kopf.Error(msg, delay=10)
> AttributeError: module 'kopf' has no attribute 'Error'
> [2022-11-23 15:47:42,760] kopf.objects         [DEBUG   ] [tls-kafka/confluent-schema-registry] Patching with: {'metadata': {'annotations': {'kopf.zalando.org/create_registry': '{"started":"2022-11-23T08:18:50.979989","delayed":"2022-11-23T15:48:42.760410","purpose":"create","retries":438,"success":false,"failure":false,"message":"module \'kopf\' has no attribute \'Error\'"}', 'kopf.zalando.org/touch-dummy': None}}, 'status': {'kopf': {'progress': {'create_registry': {'started': '2022-11-23T08:18:50.979989', 'stopped': None, 'delayed': '2022-11-23T15:48:42.760410', 'purpose': 'create', 'retries': 438, 'success': False, 'failure': False, 'message': "module 'kopf' has no attribute 'Error'", 'subrefs': None}}}}}
> [2022-11-23 15:47:42,788] kopf.objects         [WARNING ] [tls-kafka/confluent-schema-registry] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'create_registry': {'started': '2022-11-23T08:18:50.979989', 'stopped': None, 'delayed': '2022-11-23T15:48:42.760410', 'purpose': 'create', 'retries': 438, 'success': False, 'failure': False, 'message': "module 'kopf' has no attribute 'Error'", 'subrefs': None}}}}, None),)
> [2022-11-23 15:47:42,788] kopf.objects         [DEBUG   ] [tls-kafka/confluent-schema-registry] Sleeping was skipped because of the patch, 59.999766 seconds left.
> ```
> 
> Using this manifest for StrimziSchemaRegistry
> 
> ```
> apiVersion: roundtable.lsst.codes/v1beta1
> kind: StrimziSchemaRegistry
> metadata:
>   name: confluent-schema-registry
> spec:
>   strimziVersion: v1beta2
>   listener: tls
>   securityProtocol: tls
>   compatibilityLevel: forward
>   registryImage: confluentinc/cp-schema-registry
>   registryImageTag: "7.2.2"  
>   cpuLimit: ""
>   cpuRequest: ""
>   memoryLimit: ""
>   memoryRequest: ""
> ```
> 
> I am stuck now, with no idea where to debug. Any help is appreciated.

Hi @bkak  - were you able to resolve this issue ? I'm facing similar issue

**Comment by victor-wyk** [comment]
Hello I am facing the exact issue, please advise

**Comment by Hongbo-Miao** [comment]
Received same error. 🥲

**Comment by Hongbo-Miao** [comment]
Not related with this issue, but [here](https://stackoverflow.com/questions/76157961/how-to-install-confluent-schema-registry-using-bitnami-helm-chart-for-external-k) is solution using Confluent Schema Registry packaged by Bitnami in case it helps some people.
It works well with Kafka created by Strimzi too. 😃

**Comment by afausti** [comment]
Fixed via #109

**Comment by lucasfcnunes** [comment]
Thanks for this and your latest changes in the repo, @afausti!
