### ISSUE TITLE
 module 'kopf' has no attribute 'Error'

### ISSUE THREAD

**Issue by victor-wyk** [lsst-sqre/strimzi-registry-operator#91]
`[2023-01-16 04:01:25,813] kubernetes.client.re [DEBUG   ] response body: {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"KafkaUser","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"kafka.strimzi.io/v1beta2\",\"kind\":\"KafkaUser\",\"metadata\":{\"annotations\":{},\"labels\":{\"strimzi.io/cluster\":\"kmon-strimzi-kafka-cluster\"},\"name\":\"confluent-schema-registry\",\"namespace\":\"kmon-k1670\"},\"spec\":{\"authentication\":{\"type\":\"tls\"},\"authorization\":{\"acls\":[{\"operation\":\"All\",\"resource\":{\"name\":\"registry-schemas\",\"patternType\":\"literal\",\"type\":\"topic\"},\"type\":\"allow\"},{\"operation\":\"All\",\"resource\":{\"name\":\"schema-registry\",\"patternType\":\"prefix\",\"type\":\"group\"},\"type\":\"allow\"},{\"operation\":\"Describe\",\"resource\":{\"name\":\"__consumer_offsets\",\"patternType\":\"literal\",\"type\":\"topic\"},\"type\":\"allow\"}],\"type\":\"simple\"}}}\n"},"creationTimestamp":"2023-01-16T03:58:53Z","generation":1,"labels":{"strimzi.io/cluster":"kmon-strimzi-kafka-cluster"},"managedFields":[{"apiVersion":"kafka.strimzi.io/v1beta2","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:strimzi.io/cluster":{}}},"f:spec":{".":{},"f:authentication":{".":{},"f:type":{}},"f:authorization":{".":{},"f:acls":{},"f:type":{}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2023-01-16T03:58:53Z"},{"apiVersion":"kafka.strimzi.io/v1beta2","fieldsType":"FieldsV1","fieldsV1":{"f:status":{".":{},"f:conditions":{},"f:observedGeneration":{}}},"manager":"strimzi-user-operator","operation":"Update","subresource":"status","time":"2023-01-16T04:00:07Z"}],"name":"confluent-schema-registry","namespace":"kmon-k1670","resourceVersion":"206897725","uid":"478ea401-0ee4-4ed1-a6aa-7564435fbf1c"},"spec":{"authentication":{"type":"tls"},"authorization":{"acls":[{"operation":"All","resource":{"name":"registry-schemas","patternType":"literal","type":"topic"},"type":"allow"},{"operation":"All","resource":{"name":"schema-registry","patternType":"prefix","type":"group"},"type":"allow"},{"operation":"Describe","resource":{"name":"__consumer_offsets","patternType":"literal","type":"topic"},"type":"allow"}],"type":"simple"}},"status":{"conditions":[{"lastTransitionTime":"2023-01-16T04:00:07.566038Z","message":"Simple authorization ACL rules are configured but not supported in the Kafka cluster configuration.","reason":"InvalidResourceException","status":"True","type":"NotReady"},{"lastTransitionTime":"2023-01-16T04:00:07.498099Z","message":"In API version kafka.strimzi.io/v1beta2 the operation property at path spec.authorization.acls.operation has been deprecated, and should now be configured using spec.authorization.acls[*].operations.","reason":"DeprecatedFields","status":"True","type":"Warning"}],"observedGeneration":1}}

[2023-01-16 04:01:25,818] kubernetes.client.re [DEBUG   ] response body: {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"Kafka","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"kafka.strimzi.io/v1beta2\",\"kind\":\"Kafka\",\"metadata\":{\"annotations\":{},\"name\":\"kmon-strimzi-kafka-cluster\",\"namespace\":\"kmon-k1670\"},\"spec\":{\"entityOperator\":{\"template\":{\"pod\":{\"metadata\":{\"annotations\":{\"prometheus.io/scrape\":\"true\",\"sidecar.istio.io/inject\":\"false\"}}}},\"topicOperator\":{},\"userOperator\":{}},\"kafka\":{\"config\":{\"auto.create.topics.enable\":false,\"controlled.shutdown.enable\":true,\"default.replication.factor\":3,\"group.initial.rebalance.delay.ms\":1000,\"log.cleanup.policy\":\"delete\",\"log.retention.check.interval.ms\":300000,\"log.retention.ms\":604800000,\"log.segment.bytes\":1073741824,\"min.insync.replicas\":2,\"num.io.threads\":8,\"num.network.threads\":3,\"num.partitions\":50,\"num.recovery.threads.per.data.dir\":1,\"offsets.topic.num.partitions\":50,\"offsets.topic.replication.factor\":3,\"socket.receive.buffer.bytes\":102400,\"socket.request.max.bytes\":104857600,\"socket.send.buffer.bytes\":102400},\"listeners\":[{\"name\":\"plain\",\"port\":9092,\"tls\":false,\"type\":\"internal\"},{\"name\":\"tls\",\"port\":9093,\"tls\":true,\"type\":\"internal\"}],\"livenessProbe\":{\"initialDelaySeconds\":15,\"timeoutSeconds\":5},\"metricsConfig\":{\"type\":\"jmxPrometheusExporter\",\"valueFrom\":{\"configMapKeyRef\":{\"key\":\"kafka-metrics-config.yml\",\"name\":\"kafka-metrics\"}}},\"readinessProbe\":{\"initialDelaySeconds\":15,\"timeoutSeconds\":5},\"replicas\":3,\"storage\":{\"type\":\"jbod\",\"volumes\":[{\"class\":\"alicloud-disk-essd-ha\",\"deleteClaim\":true,\"id\":0,\"size\":\"20Gi\",\"type\":\"persistent-claim\"}]},\"template\":{\"pod\":{\"metadata\":{\"annotations\":{\"prometheus.io/port\":\"9404\",\"prometheus.io/scrape\":\"true\",\"sidecar.istio.io/inject\":\"false\"}},\"securityContext\":{\"runAsUser\":0}}},\"version\":\"3.3.1\"},\"zookeeper\":{\"livenessProbe\":{\"initialDelaySeconds\":15,\"timeoutSeconds\":5},\"metricsConfig\":{\"type\":\"jmxPrometheusExporter\",\"valueFrom\":{\"configMapKeyRef\":{\"key\":\"zookeeper-metrics-config.yml\",\"name\":\"kafka-metrics\"}}},\"readinessProbe\":{\"initialDelaySeconds\":15,\"timeoutSeconds\":5},\"replicas\":3,\"storage\":{\"class\":\"alicloud-disk-essd-ha\",\"deleteClaim\":true,\"size\":\"20Gi\",\"type\":\"persistent-claim\"},\"template\":{\"pod\":{\"metadata\":{\"annotations\":{\"prometheus.io/port\":\"9404\",\"prometheus.io/scrape\":\"true\",\"sidecar.istio.io/inject\":\"false\"}},\"securityContext\":{\"runAsUser\":0}}}}}}\n"},"creationTimestamp":"2023-01-16T03:58:46Z","generation":1,"managedFields":[{"apiVersion":"kafka.strimzi.io/v1beta2","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{".":{},"f:entityOperator":{".":{},"f:template":{".":{},"f:pod":{".":{},"f:metadata":{".":{},"f:annotations":{".":{},"f:prometheus.io/scrape":{},"f:sidecar.istio.io/inject":{}}}}},"f:topicOperator":{},"f:userOperator":{}},"f:kafka":{".":{},"f:config":{".":{},"f:auto.create.topics.enable":{},"f:controlled.shutdown.enable":{},"f:default.replication.factor":{},"f:group.initial.rebalance.delay.ms":{},"f:log.cleanup.policy":{},"f:log.retention.check.interval.ms":{},"f:log.retention.ms":{},"f:log.segment.bytes":{},"f:min.insync.replicas":{},"f:num.io.threads":{},"f:num.network.threads":{},"f:num.partitions":{},"f:num.recovery.threads.per.data.dir":{},"f:offsets.topic.num.partitions":{},"f:offsets.topic.replication.factor":{},"f:socket.receive.buffer.bytes":{},"f:socket.request.max.bytes":{},"f:socket.send.buffer.bytes":{}},"f:listeners":{},"f:livenessProbe":{".":{},"f:initialDelaySeconds":{},"f:timeoutSeconds":{}},"f:metricsConfig":{".":{},"f:type":{},"f:valueFrom":{".":{},"f:configMapKeyRef":{".":{},"f:key":{},"f:name":{}}}},"f:readinessProbe":{".":{},"f:initialDelaySeconds":{},"f:timeoutSeconds":{}},"f:replicas":{},"f:storage":{".":{},"f:type":{},"f:volumes":{}},"f:template":{".":{},"f:pod":{".":{},"f:metadata":{".":{},"f:annotations":{".":{},"f:prometheus.io/port":{},"f:prometheus.io/scrape":{},"f:sidecar.istio.io/inject":{}}},"f:securityContext":{".":{},"f:runAsUser":{}}}},"f:version":{}},"f:zookeeper":{".":{},"f:livenessProbe":{".":{},"f:initialDelaySeconds":{},"f:timeoutSeconds":{}},"f:metricsConfig":{".":{},"f:type":{},"f:valueFrom":{".":{},"f:configMapKeyRef":{".":{},"f:key":{},"f:name":{}}}},"f:readinessProbe":{".":{},"f:initialDelaySeconds":{},"f:timeoutSeconds":{}},"f:replicas":{},"f:storage":{".":{},"f:class":{},"f:deleteClaim":{},"f:size":{},"f:type":{}},"f:template":{".":{},"f:pod":{".":{},"f:metadata":{".":{},"f:annotations":{".":{},"f:prometheus.io/port":{},"f:prometheus.io/scrape":{},"f:sidecar.istio.io/inject":{}}},"f:securityContext":{".":{},"f:runAsUser":{}}}}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2023-01-16T03:58:46Z"},{"apiVersion":"kafka.strimzi.io/v1beta2","fieldsType":"FieldsV1","fieldsV1":{"f:status":{".":{},"f:clusterId":{},"f:conditions":{},"f:listeners":{},"f:observedGeneration":{}}},"manager":"strimzi-cluster-operator","operation":"Update","subresource":"status","time":"2023-01-16T04:00:23Z"}],"name":"kmon-strimzi-kafka-cluster","namespace":"kmon-k1670","resourceVersion":"206897942","uid":"9411a6cf-9547-430e-bd0b-d4d8f22364bd"},"spec":{"entityOperator":{"template":{"pod":{"metadata":{"annotations":{"prometheus.io/scrape":"true","sidecar.istio.io/inject":"false"}}}},"topicOperator":{},"userOperator":{}},"kafka":{"config":{"auto.create.topics.enable":false,"controlled.shutdown.enable":true,"default.replication.factor":3,"group.initial.rebalance.delay.ms":1000,"log.cleanup.policy":"delete","log.retention.check.interval.ms":300000,"log.retention.ms":604800000,"log.segment.bytes":1073741824,"min.insync.replicas":2,"num.io.threads":8,"num.network.threads":3,"num.partitions":50,"num.recovery.threads.per.data.dir":1,"offsets.topic.num.partitions":50,"offsets.topic.replication.factor":3,"socket.receive.buffer.bytes":102400,"socket.request.max.bytes":104857600,"socket.send.buffer.bytes":102400},"listeners":[{"name":"plain","port":9092,"tls":false,"type":"internal"},{"name":"tls","port":9093,"tls":true,"type":"internal"}],"livenessProbe":{"initialDelaySeconds":15,"timeoutSeconds":5},"metricsConfig":{"type":"jmxPrometheusExporter","valueFrom":{"configMapKeyRef":{"key":"kafka-metrics-config.yml","name":"kafka-metrics"}}},"readinessProbe":{"initialDelaySeconds":15,"timeoutSeconds":5},"replicas":3,"storage":{"type":"jbod","volumes":[{"class":"alicloud-disk-essd-ha","deleteClaim":true,"id":0,"size":"20Gi","type":"persistent-claim"}]},"template":{"pod":{"metadata":{"annotations":{"prometheus.io/port":"9404","prometheus.io/scrape":"true","sidecar.istio.io/inject":"false"}},"securityContext":{"runAsUser":0}}},"version":"3.3.1"},"zookeeper":{"livenessProbe":{"initialDelaySeconds":15,"timeoutSeconds":5},"metricsConfig":{"type":"jmxPrometheusExporter","valueFrom":{"configMapKeyRef":{"key":"zookeeper-metrics-config.yml","name":"kafka-metrics"}}},"readinessProbe":{"initialDelaySeconds":15,"timeoutSeconds":5},"replicas":3,"storage":{"class":"alicloud-disk-essd-ha","deleteClaim":true,"size":"20Gi","type":"persistent-claim"},"template":{"pod":{"metadata":{"annotations":{"prometheus.io/port":"9404","prometheus.io/scrape":"true","sidecar.istio.io/inject":"false"}},"securityContext":{"runAsUser":0}}}}},"status":{"clusterId":"tGE7pg2lRG-II-WABx0asQ","conditions":[{"lastTransitionTime":"2023-01-16T04:00:23.811771Z","status":"True","type":"Ready"}],"listeners":[{"addresses":[{"host":"kmon-strimzi-kafka-cluster-kafka-bootstrap.kmon-k1670.svc","port":9092}],"bootstrapServers":"kmon-strimzi-kafka-cluster-kafka-bootstrap.kmon-k1670.svc:9092","type":"plain"},{"addresses":[{"host":"kmon-strimzi-kafka-cluster-kafka-bootstrap.kmon-k1670.svc","port":9093}],"bootstrapServers":"kmon-strimzi-kafka-cluster-kafka-bootstrap.kmon-k1670.svc:9093","certificates":["-----BEGIN CERTIFICATE-----\nMIIFLTCCAxWgAwIBAgIULPeYuhUtY5F8MxrXH7WL7xlH8s0wDQYJKoZIhvcNAQEN\nBQAwLTETMBEGA1UECgwKaW8uc3RyaW16aTEWMBQGA1UEAwwNY2x1c3Rlci1jYSB2\nMDAeFw0yMzAxMTYwMzU4NDZaFw0yNDAxMTYwMzU4NDZaMC0xEzARBgNVBAoMCmlv\nLnN0cmltemkxFjAUBgNVBAMMDWNsdXN0ZXItY2EgdjAwggIiMA0GCSqGSIb3DQEB\nAQUAA4ICDwAwggIKAoICAQCWi16UQaU7CjErrUMMSiBMcbRxvqMw69sy588nfCwl\nApJG+Ccy/FdziGQoHomI3vqFeZhNXNMzQrFaDYGNTHtIe7LTvJ1uxtD1KE8MXKy9\n9+MR797JCKMk/EnPcpKOmgrxrml21WLZDK/Fp3raj7hcTsvTr2mSGg2tp7RtJkLx\nKiQexf/M29OLK+Hg/4OsVY0v8MA48/rNoVned9Dm3szsF02kM62rpy9yqptRYkzi\nxssq1Aik7OQDNNVm0CCPHSbI1ohLMEDlcKtlTBLxT/rLt61FESqVj+Ahl0kQ+tA9\naS1ggXbb0dtz8wtxTMEjVcUiru7DSZ8u1nFwaUYOn6o9W6Ygi3eZ1OKWE7EmLd9s\niolOzg8D4wnSwFBzfTM8Oi4oI+Gm1YaeBZv8HCPHKj82dnNG77XNZL2Ztd4jm1Og\nmr85r+4LCi++2KTqah6berwZcwnXMw4KiUG1sjnN4JMvyp25ANLzgGGxAuyW43AT\nMbjwiOBFUnHKLjagX5jzeVo1+c+H+GoCpMnSzGwnEZJPfpki3aM1E+SmAVxBDjm+\nzBS+mO2cmDgcEACqIzTRnqa4upBG7G4i9rObfwBWQa+65HSku14v2X1qaL8/3Oxh\n3WaneuW3/JefthaiadQwkRBb54Qee8InuOv+8uskc2G5Qm4FHkxLai7uDw4eCkpv\nJwIDAQABo0UwQzAdBgNVHQ4EFgQUlzhQc6TAGzQymp5w39AZzkJlBB4wEgYDVR0T\nAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQENBQADggIB\nAFCXy+kBauqGxZEcMW4S7ZOq7FiaPrKCkoph7kUzxETw1oIHwZ/BnhQf/kehE3Ya\nrfeN5mh+3PXF2CF5GW5B8buImerZrUA1jF3Cc2JVjHm2wrwhuYLbfVOsUXB6mklh\nJHfuz5oKzevvNdVylu+1Xa+mGImVFUTvACEV1/uyO0mGnAYMpFjKdpF93AHw3gu4\ngXGUpO4/G0DqtAnVjAw/8latyQR6ybJquwJhFnYjYNlcVOcSi9Amh0fCxkwl18qf\nxOaXmYMQBYYvHbc5x29vbxDBRu47Hv982RVBT+zjRHYJhts9UxIsp/g8XCzYk6fY\nkrFG7J7WXfJndT15RCZRbvoUvgzBaL+PRNkwJEB10r7TnEugEQ5N3LxGlxc+VKTL\nK9gS2OF/zs/yubKgmpJ5It8EkfjoiFMYfHntKPnYFhPM1VKmNa7oaUdq0hJhVoQC\n+SBv0h4/RZUYpmGDp00S5nCZyROc3k+Btnj1jttxdizvg4jppJX4BLuA8CsHcpXS\n1Qn29/VfZfjY4uNWX+UhbxeFcWpYS7+5HZ2m4yL0ZZbSCeXdde1CWaQUwtslzM4+\n/EBR0y7vwznN3I89527PpLmLiDDRRfrRlc8GLY7OKDzZ24t+l28H8d4j/wmadf6n\njq/WkwxR3djcF7xVlxlimys8yVaGdgq1kjQZCsrItB8H\n-----END CERTIFICATE-----\n"],"type":"tls"}],"observedGeneration":1}}

[2023-01-16 04:01:25,818] kopf.objects         [ERROR   ] [kmon-k1670/confluent-schema-registry] Handler 'create_registry' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
  File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
    result = await invocation.invoke(
  File "/opt/venv/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/strimziregistryoperator/handlers/createregistry.py", line 131, in create_registry
    bootstrap_server = get_kafka_bootstrap_server(
  File "/opt/venv/lib/python3.10/site-packages/strimziregistryoperator/deployments.py", line 83, in get_kafka_bootstrap_server
    raise kopf.Error(msg, delay=10)
AttributeError: module 'kopf' has no attribute 'Error'`

**Comment by victor-wyk** [comment]
Hello we have been looking for a straight forward solution for this error but so far this is a dead end, please help

**Comment by karanalang** [comment]
I've the same issue

**Comment by afausti** [comment]
Fixed via #109
